### PR TITLE
Add check_os_flavors.m4

### PR DESCRIPTION
**Pull request by rhc54**
Direct copy from HEAD of PRRTE master branch, replacing PRTE with OAC (both upper/lower cases)

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jsquyres** [comment]
I have no objections, but @bwbarrett is more the AC expert than me...

**Comment by bwbarrett** [comment]
I'd really like to remove the TCP checks from this macro, given they're not related to the core function of the macro.  Otherwise, I'm ok moving it.

**Comment by rhc54** [comment]
ok, i'll take a crack at that in the morning.

**Comment by rhc54** [comment]
> I'd really like to remove the TCP checks from this macro

Done!

**Review by jsquyres — APPROVED** [review]

**Comment by rhc54** [comment]
Let me know if you'd like me to squash these - I didn't so you could see the change to remove the TCP code.

**Comment by jsquyres** [comment]
Squash would be awesome; thanks!

**Comment by rhc54** [comment]
Squashed!

**Review by bwbarrett — APPROVED** [review]

**Pull request merged**
